name: Lua Busted (Alpine)
description: Busted
inputs:
  args:
    description: Arguments passed to busted
    required: false
    default: "."
runs:
  using: docker
  image: docker://ghcr.io/louisroyer-gh-actions/busted:1.1.1
  args:
    - ${{ inputs.args }}
branding:
  icon: chevrons-up
  color: blue
